default_agent: ttyd_agent_lambda
agents:
  ttyd_agent:
    name: ttyd_agent
    entrypoint: /home/tkricemo/talktoyourdata/app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/tkricemo/talktoyourdata
    aws:
      execution_role: arn:aws:iam::499495551785:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-bc005b1778
      execution_role_auto_create: false
      account: '499495551785'
      region: us-east-1
      ecr_repository: 499495551785.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ttyd_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ttyd_agent-YkSIL0Cl6O
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:499495551785:runtime/ttyd_agent-YkSIL0Cl6O
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ttyd_agent-builder
      execution_role: arn:aws:iam::499495551785:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-bc005b1778
      source_bucket: bedrock-agentcore-codebuild-sources-499495551785-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: ttyd_agent_mem-M2PoxdHjS7
      memory_arn: null
      memory_name: ttyd_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  ttyd_agent_lambda:
    name: ttyd_agent_lambda
    entrypoint: /home/tkricemo/talktoyourdata/app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/tkricemo/talktoyourdata
    aws:
      execution_role: arn:aws:iam::499495551785:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e23adb776f
      execution_role_auto_create: false
      account: '499495551785'
      region: us-east-1
      ecr_repository: 499495551785.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ttyd_agent_lambda
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ttyd_agent_lambda-vXfwZ5GhaC
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:499495551785:runtime/ttyd_agent_lambda-vXfwZ5GhaC
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ttyd_agent_lambda-builder
      execution_role: arn:aws:iam::499495551785:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e23adb776f
      source_bucket: bedrock-agentcore-codebuild-sources-499495551785-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: ttyd_agent_mem-M2PoxdHjS7
      memory_arn: null
      memory_name: ttyd_agent_lambda_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
